name: "Unit/Coverage Tests"

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    outputs:
      msg: ${{ steps.results.outputs.content }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Run unit tests and coverage test
        id: test-coverage
        run: |
          go test -cover -v
